In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [9]:
df = pd.read_csv("sales.csv")

In [11]:
df.head()

,Order Date,Customer Name,State,Category,Sub-Category,Product Name,Sales,Quantity,Profit,Month,Year
0,44199,Darren Powers,Texas,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.45,2,5.55,Jan,2021
1,44200,Phillina Ober,Illinois,Office Supplies,Labels,Avery 508,11.78,3,4.27,Jan,2021
2,44200,Phillina Ober,Illinois,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.74,3,-64.77,Jan,2021
3,44200,Phillina Ober,Illinois,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.54,2,-5.49,Jan,2021
4,44201,Mick Brown,Pennsylvania,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.54,3,4.88,Jan,2021

Data Exploration

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8314 entries, 0 to 8313
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order Date     8314 non-null   int64
 1   Customer Name  8314 non-null   object
 2   State          8314 non-null   object
 3   Category       8314 non-null   object
 4   Sub-Category   8314 non-null   object
 5   Product Name   8314 non-null   object
 6   Sales          8314 non-null   float64
 7   Quantity       8314 non-null   int64
 8   Profit         8314 non-null   float64
 9   Month          8314 non-null   object
 10  Year           8314 non-null   int64
dtypes: float64(2), int64(3), object(6)
memory usage: 714.6+ KB

In [13]:
df.describe()

         Order Date         Sales     Quantity       Profit         Year
count   8314.000000   8314.000000  8314.000000  8314.000000  8314.000000
mean   44935.875511    232.004794     3.789752    29.824521  2022.464518
std      372.606632    629.917690     2.216657   232.045895     1.058839
min    44199.000000      0.440000     1.000000 -6599.980000  2021.000000
25%    44606.000000     17.340000     2.000000     1.722500  2022.000000
50%    44949.000000     55.000000     3.000000     8.790000  2023.000000
75%    45252.000000    211.960000     5.000000    29.987500  2023.000000
max    45535.000000  22638.480000    14.000000  8399.980000  2024.000000

In [14]:
df.isnull().sum()

Order Date       0
Customer Name    0
State            0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Profit           0
Month            0
Year             0
dtype: int64

In [20]:
df.drop_duplicates(inplace = True)

#covert date
df["Order Date"] = pd.to_datetime(df["Order Date"])

#ensure month and year column exist
df["Month"] = df["Order Date"].dt.month
df["Year"] = df["Order Date"].dt.year


#Feature Engineering: profit margin
df["Profit Margin"] = df["Profit"] / df["Sales"]


#flag top performing produacts (sales > 90 percent)
top_sales_thresholds = df["Sales"].quantile(0.9)
df["Top products"] = np.where(df["Sales"] >= top_sales_thresholds, "Yes", "No")